export const LOGIN_REQUEST = 'LOGIN-REQUEST';
export const LOGIN_FAILURE = 'LOGIN-FAILURE';
export const LOGIN_SUCESS = 'LOGIN-SUCESS';

export const REGISTER_REQUEST = 'REGISTER-REQUEST';
export const REGISTER_SUCESS = 'REGISTER-SUCESS';
export const REGISTER_FAILURE = 'REGISTER-FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';