export const BOTAO_CLICADO_SUCESS = 'BOTAO-CLICADO-SUCESS';
export const BOTAO_CLICADO_FAILURE = 'BOTAO-CLICADO-FAILURE';
export const BOTAO_CLICADO_REQUEST = 'BOTAO-CLICADO-REQUEST';

export const LOGIN_REQUEST = 'LOGIN-REQUEST';
export const LOGIN_FAILURE = 'LOGIN-FAILURE';
export const LOGIN_SUCESS = 'LOGIN-SUCESS';

export const REGISTER_REQUEST = 'REGISTER-REQUEST';
export const REGISTER_SUCESS = 'REGISTER-SUCESS';
export const REGISTER_FAILURE = 'REGISTER-FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';